FLAGS = [
    "early-inlining", "function-cse", "keep-static-consts",
    "peephole", "split-ivn-in-unroller", "tree-vect-loop-version",
    "cprop-registers", "defer-pop", "guess-branch-probability",
    "if-conversion", "if-conversion2", "ipa-pure-const",
    "ipa-reference", "loop-optimize", "merge-constants",
    "tree-ccp", "tree-ch", "tree-copy-prop", "tree-copyrename",
    "tree-dce", "tree-dominator-opts", "tree-dse", "tree-fre",
    "tree-lrs", "tree-salias", "tree-sink", "tree-sra",
    "tree-ter", "unit-at-a-time", "align-functions=0",
    "align-jumps=0", "align-labels=0", "align-loops=0",
    "caller-saves", "crossjumping", "cse-follow-jumps",
    "cse-skip-blocks", "delete-null-pointer-checks", "expensive-optimizations",
    "gcse", "ipa-type-escape", "optimize-sibling-calls", "peephole2",
    "regmove", "reorder-blocks", "reorder-functions",
    "rerun-cse-after-loop", "rerun-loop-opt", "schedule-insns2",
    "strength-reduce", "strict-aliasing", "thread-jumps", "tree-pre",
    "tree-store-ccp", "tree-store-copy-prop", "tree-vrp", "gcse-after-reload",
    "gcse-after-reload", "unswitch-loops",
    "-fno-reorder-blocks-and-partition"
]