# GA Factors
GENERATIONS = 50
POPULATION_SIZE = 10
CROSSOVER_RATE = 0.6
MUTATION_RATE = 0.01

# Meta Data names
META_DATA_EXEC_TIME = 'execution-time'
META_DATA_COMPILE_TIME = 'compile-time'
META_DATA_BIN_SIZE = 'bin-size'
